/**
 * Seed the `fleet_apps` D1 table with all known fleet apps.
 *
 * This migrates the formerly-hardcoded data from fleet-registry.ts into D1.
 * Uses INSERT OR REPLACE so it's idempotent — safe to re-run.
 *
 * Usage:
 *   npx wrangler d1 execute control-plane-db --local --file=tools/seed-fleet-apps.sql
 *   npx wrangler d1 execute control-plane-db --remote --file=tools/seed-fleet-apps.sql
 */

const FLEET_APPS = [
  { name: 'austin-texas-net', url: 'https://austin-texas.net', gaPropertyId: '526067189', githubRepo: 'narduk-enterprises/austin-texas-net' },
  { name: 'ai-media-gen', url: 'https://ai-media-gen.nard.uk', gaPropertyId: null, githubRepo: 'narduk-enterprises/ai-media-gen' },
  { name: 'circuit-breaker-online', url: 'https://circuitbreaker.online', gaPropertyId: '520350533', githubRepo: 'narduk-enterprises/circuit-breaker-online' },
  { name: 'clawdle', url: 'https://clawdle.nard.uk', gaPropertyId: '526225128', githubRepo: 'narduk-enterprises/clawdle' },
  { name: 'drift-map', url: 'https://drift-map.nard.uk', gaPropertyId: '526978811', posthogAppName: 'Drift Map', githubRepo: 'narduk-enterprises/drift-map' },
  { name: 'enigma-box', url: 'https://enigma-box.nard.uk', gaPropertyId: '526992343', githubRepo: 'narduk-enterprises/enigma-box' },
  { name: 'favicon-checker', url: 'https://favicon-checker.nard.uk', gaPropertyId: null, githubRepo: 'narduk-enterprises/favicon-checker' },
  { name: 'flashcard-pro', url: 'https://flashcard-pro.nard.uk', gaPropertyId: '526595766', githubRepo: 'narduk-enterprises/flashcard-pro' },
  { name: 'imessage-dictionary', url: 'https://dictionary.nard.uk', gaPropertyId: '526234707', githubRepo: 'narduk-enterprises/imessage-dictionary' },
  { name: 'nagolnagemluapleira', url: 'https://nagolnagemluapleira.nard.uk', gaPropertyId: '526231074', githubRepo: 'narduk-enterprises/nagolnagemluapleira' },
  { name: 'narduk-enterprises-portfolio', url: 'https://portfolio.nard.uk', gaPropertyId: '526233051', githubRepo: 'narduk-enterprises/narduk-enterprises-portfolio' },
  { name: 'neon-sewer-raid', url: 'https://neon-sewer-raid.nard.uk', gaPropertyId: '526228839', githubRepo: 'narduk-enterprises/neon-sewer-raid' },
  { name: 'ogpreview-app', url: 'https://ogpreview.app', gaPropertyId: '526214794', githubRepo: 'narduk-enterprises/ogpreview-app' },
  { name: 'old-austin-grouch', url: 'https://grouch.austin-texas.net', gaPropertyId: '526226582', githubRepo: 'narduk-enterprises/old-austin-grouch' },
  { name: 'papa-everetts-pizza', url: 'https://papaeverettspizza.com', gaPropertyId: '526158939', posthogAppName: "Papa Everett's Pizza Co.", githubRepo: 'narduk-enterprises/papa-everetts-pizza' },
  { name: 'sailing-passage-map', url: 'https://passages.nard.uk', gaPropertyId: '526974566', githubRepo: 'narduk-enterprises/sailing-passage-map' },
  { name: 'tiny-invoice', url: 'https://tiny-invoice.nard.uk', gaPropertyId: '526997389', githubRepo: 'narduk-enterprises/tiny-invoice' },
  { name: 'video-grab', url: 'https://video-grab.nard.uk', gaPropertyId: '526953881', githubRepo: 'narduk-enterprises/video-grab' },
]

// Generate SQL
const now = new Date().toISOString()
const lines = FLEET_APPS.map((app) => {
  const name = app.name
  const url = app.url
  const dopplerProject = app.name
  const gaPropertyId = app.gaPropertyId ? `'${app.gaPropertyId}'` : 'NULL'
  const posthogAppName = (app as Record<string, unknown>).posthogAppName ? `'${String((app as Record<string, unknown>).posthogAppName).replace(/'/g, "''")}'` : 'NULL'
  const githubRepo = app.githubRepo ? `'${app.githubRepo}'` : 'NULL'
  const isActive = (app as Record<string, unknown>).isActive === false ? 0 : 1
  return `INSERT OR REPLACE INTO fleet_apps (name, url, doppler_project, ga_property_id, posthog_app_name, github_repo, is_active, created_at, updated_at) VALUES ('${name}', '${url}', '${dopplerProject}', ${gaPropertyId}, ${posthogAppName}, ${githubRepo}, ${isActive}, '${now}', '${now}');`
})

console.log('-- Fleet Apps Seed Data')
console.log('-- Generated by tools/seed-fleet-apps.ts')
console.log(`-- Run: npx wrangler d1 execute control-plane-db --local --file=tools/seed-fleet-apps.sql`)
console.log(`-- Or:  npx wrangler d1 execute control-plane-db --remote --file=tools/seed-fleet-apps.sql`)
console.log('')
for (const line of lines) {
  console.log(line)
}
