/**
 * Seed the `fleet_apps` D1 table from the managed-repo catalog.
 *
 * Uses INSERT OR REPLACE so it's idempotent and deterministic.
 *
 * Usage:
 *   npx wrangler d1 execute control-plane-db --local --file=tools/seed-fleet-apps.sql
 *   npx wrangler d1 execute control-plane-db --remote --file=tools/seed-fleet-apps.sql
 */

import { getPublicFleetApps } from '../apps/web/server/data/managed-repos'
import { serializeFleetAuthProviders } from '../apps/web/server/data/fleet-auth'
import { deriveSeedNuxtPort } from '../apps/web/server/utils/nuxt-port'

function sqlString(value: string | null): string {
  return value === null ? 'NULL' : `'${value.replace(/'/g, "''")}'`
}

const nowExpr = "STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')"
const lines = getPublicFleetApps().map((app, index) => {
  const nuxtPort = deriveSeedNuxtPort(index)
  return `INSERT INTO fleet_apps (name, url, doppler_project, nuxt_port, ga_property_id, ga_measurement_id, posthog_app_name, github_repo, auth_enabled, redirect_base_url, login_path, callback_path, logout_path, confirm_path, reset_path, public_signup, providers, require_mfa, is_active, created_at, updated_at) VALUES (${sqlString(app.name)}, ${sqlString(app.url)}, ${sqlString(app.dopplerProject)}, ${nuxtPort}, ${sqlString(app.gaPropertyId)}, ${sqlString(app.gaMeasurementId)}, ${sqlString(app.posthogAppName)}, ${sqlString(app.githubRepo)}, ${app.authEnabled ? 1 : 0}, ${sqlString(app.redirectBaseUrl)}, ${sqlString(app.loginPath)}, ${sqlString(app.callbackPath)}, ${sqlString(app.logoutPath)}, ${sqlString(app.confirmPath)}, ${sqlString(app.resetPath)}, ${app.publicSignup ? 1 : 0}, ${sqlString(serializeFleetAuthProviders(app.providers))}, ${app.requireMfa ? 1 : 0}, ${app.isActive ? 1 : 0}, ${nowExpr}, ${nowExpr}) ON CONFLICT(name) DO UPDATE SET url = excluded.url, doppler_project = excluded.doppler_project, nuxt_port = COALESCE(fleet_apps.nuxt_port, excluded.nuxt_port), ga_property_id = excluded.ga_property_id, ga_measurement_id = excluded.ga_measurement_id, posthog_app_name = excluded.posthog_app_name, github_repo = excluded.github_repo, auth_enabled = excluded.auth_enabled, redirect_base_url = excluded.redirect_base_url, login_path = excluded.login_path, callback_path = excluded.callback_path, logout_path = excluded.logout_path, confirm_path = excluded.confirm_path, reset_path = excluded.reset_path, public_signup = excluded.public_signup, providers = excluded.providers, require_mfa = excluded.require_mfa, is_active = excluded.is_active, updated_at = excluded.updated_at;`
})

console.log('-- Fleet Apps Seed Data')
console.log('-- Generated by tools/seed-fleet-apps.ts from server/data/managed-repos.ts')
console.log(
  `-- Run: npx wrangler d1 execute control-plane-db --local --file=tools/seed-fleet-apps.sql`,
)
console.log(
  `-- Or:  npx wrangler d1 execute control-plane-db --remote --file=tools/seed-fleet-apps.sql`,
)
console.log('')
for (const line of lines) {
  console.log(line)
}
