/**
 * Seed the `fleet_apps` D1 table from the managed-repo catalog.
 *
 * Uses INSERT OR REPLACE so it's idempotent and deterministic.
 *
 * Usage:
 *   npx wrangler d1 execute control-plane-db --local --file=tools/seed-fleet-apps.sql
 *   npx wrangler d1 execute control-plane-db --remote --file=tools/seed-fleet-apps.sql
 */

import { getPublicFleetApps } from '../apps/web/server/data/managed-repos'

function sqlString(value: string | null): string {
  return value === null ? 'NULL' : `'${value.replace(/'/g, "''")}'`
}

const nowExpr = "STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')"
const lines = getPublicFleetApps().map((app) => {
  return `INSERT OR REPLACE INTO fleet_apps (name, url, doppler_project, ga_property_id, ga_measurement_id, posthog_app_name, github_repo, is_active, created_at, updated_at) VALUES (${sqlString(app.name)}, ${sqlString(app.url)}, ${sqlString(app.dopplerProject)}, ${sqlString(app.gaPropertyId)}, ${sqlString(app.gaMeasurementId)}, ${sqlString(app.posthogAppName)}, ${sqlString(app.githubRepo)}, ${app.isActive ? 1 : 0}, ${nowExpr}, ${nowExpr});`
})

console.log('-- Fleet Apps Seed Data')
console.log('-- Generated by tools/seed-fleet-apps.ts from server/data/managed-repos.ts')
console.log(
  `-- Run: npx wrangler d1 execute control-plane-db --local --file=tools/seed-fleet-apps.sql`,
)
console.log(
  `-- Or:  npx wrangler d1 execute control-plane-db --remote --file=tools/seed-fleet-apps.sql`,
)
console.log('')
for (const line of lines) {
  console.log(line)
}
